Repository HathorNetwork/hathor-wallet-mobile, pull requests merged in 2022-11, with the labels that each got.

#201 docs: add windows instructions to run mobile wallet
  README.md
  WINDOWS.md
Labels: design

#203 fix: invalidating history on wallet reload
  src/actions.js
  src/sagas/wallet.js
  src/screens/LoadHistoryScreen.js
Labels: bug

#207 Release v0.19.1
  README.md
  WINDOWS.md
  android/app/build.gradle
  ios/HathorMobile.xcodeproj/project.pbxproj
  package-lock.json
  package.json
  src/actions.js
  src/sagas/wallet.js
  src/screens/LoadHistoryScreen.js
  src/screens/RegisterTokenManual.js
  src/utils.js
Labels: enhancement
