Repository HathorNetwork/hathor-wallet-mobile, pull requests merged in 2023-11, with the labels that each got.

#365 fix: wallet start error when running on fullnode
  locale/da/texts.po
  locale/pt-br/texts.po
  locale/ru-ru/texts.po
  locale/texts.pot
  src/sagas/wallet.js
  src/screens/LoadWalletErrorScreen.js
Labels: bug

#370 fix: Closes keyboard on PinScreen
  src/screens/PinScreen.js
Labels: bug

#373 chore: Update `react-native-reanimated`
  package-lock.json
  package.json
Labels: dependencies

#371 (17) refactor: AlertUI color
  locale/texts.pot
  src/components/NetworkSettings/NetworkStatusBar.js
  src/screens/NetworkSettings/CustomNetworkSettingsScreen.js
  src/screens/NetworkSettings/NetworkSettingsDisclaimerScreen.js
  src/styles/themes.js
Labels: refactor

#380 Fix: Pin not working on update
  src/store.js
Labels: bug

#377 chore: version bump pr template
  .github/PULL_REQUEST_TEMPLATE.md
  .github/PULL_REQUEST_TEMPLATE/feature_branch_pr_template.md
  .github/PULL_REQUEST_TEMPLATE/version_bump_pr_template.md
Labels: enhancement

#386 Fix: QR Code registered token check
  src/sagas/helpers.js
  src/sagas/pushNotification.js
  src/screens/SendScanQRCode.js
Labels: bug

#384 fix: multiple alerts shown to QR reading
  src/screens/SendScanQRCode.js
Labels: bug

#387 Docs: QA steps to validate QR Code scanner
  QA.md
Labels: documentation

#383 Chore: Version bump helper
  Makefile
  RELEASING.md
  scripts/bump-version.js
Labels: enhancement
