Repository HathorNetwork/hathor-wallet-mobile, pull requests merged in 2023-09, with the labels that each got.

#245 feat: wallet connect on wallet-mobile
  enable-walletconnect.patch
  ios/Podfile
  locale/da/texts.po
  locale/pt-br/texts.po
  locale/ru-ru/texts.po
  src/App.js
  src/actions.js
  src/components/WalletConnect/ApproveRejectModal.js
  src/components/WalletConnect/ConnectModal.js
  src/components/WalletConnect/ModalButton.js
  src/components/WalletConnect/SignMessageModal.js
  src/components/WalletConnect/WalletConnectModal.js
  src/constants.js
  src/reducer.js
  src/sagas/featureToggle.js
  src/sagas/index.js
  src/sagas/wallet.js
  src/sagas/walletConnect.js
  src/screens/Settings.js
  src/screens/WalletConnect/WalletConnectList.js
  src/screens/WalletConnect/WalletConnectManual.js
  src/screens/WalletConnect/WalletConnectScan.js
  walletconnect.sh
Labels: design

#325 Fix: Issues raised on iOS QA
  src/App.js
  src/components/AmountTextInput.js
  src/components/HathorHeader.js
  src/components/ModalConfirmation.js
  src/constants.js
  src/screens/CreateTokenAmount.js
  src/screens/CreateTokenConfirm.js
  src/screens/CreateTokenName.js
  src/screens/CreateTokenSymbol.js
  src/screens/PaymentRequestDetail.js
  src/screens/PinScreen.js
  src/utils.js
Labels: bug

#326 Fix: iOS Colors
  src/App.js
  src/components/AmountTextInput.js
  src/components/HathorHeader.js
  src/components/SimpleInput.js
  src/screens/Settings.js
  src/styles/init.js
  src/styles/themes.js
Labels: bug

#327 refactor: string colors to themes
  src/components/CopyClipboard.js
  src/components/GlobalErrorModal.js
  src/components/HathorHeader.js
  src/components/HathorList.js
  src/components/HathorModal.js
  src/components/HathorTextInput.js
  src/components/InfoBox.js
  src/components/InputLabel.js
  src/components/ModalConfirmation.js
  src/components/NewHathorButton.js
  src/components/NumPad.js
  src/components/OfflineBar.js
  src/components/PinInput.js
  src/components/PublicExplorerListButton.js
  src/components/PushTxDetailsModal.js
  src/components/QRCodeReader.js
  src/components/ReceiveMyAddress.js
  src/components/SimpleInput.js
  src/components/SlideIndicatorBar.js
  src/components/TokenBox.js
  src/components/TokenDetails.js
  src/components/TokenSelect.js
  src/components/TxDetailsModal.js
  src/components/WalletConnect/ApproveRejectModal.js
  src/components/WalletConnect/ModalButton.js
  src/components/WalletConnect/SignMessageModal.js
  src/components/WalletConnect/WalletConnectModal.js
  src/constants.js
  src/screens/BackupWords.js
  src/screens/ChangePin.js
  src/screens/ChoosePinScreen.js
  src/screens/CreateTokenAmount.js
  src/screens/CreateTokenDetail.js
  src/screens/InitWallet.js
  src/screens/LoadHistoryScreen.js
  src/screens/MainScreen.js
  src/screens/PaymentRequestDetail.js
  src/screens/PinScreen.js
  src/screens/PushNotification.js
  src/screens/Receive.js
  src/screens/RegisterToken.js
  src/screens/Security.js
  src/screens/SendAmountInput.js
  src/screens/SendScanQRCode.js
  src/screens/TokenDetail.js
  src/screens/UnregisterToken.js
  src/screens/WalletConnect/WalletConnectList.js
  src/screens/WalletConnect/WalletConnectScan.js
  src/styles/themes.js
  src/utils.js
Labels: refactor
