Repository HathorNetwork/hathor-wallet-mobile, pull requests merged in 2023-10, with the labels that each got.

#344 chore: Pin dependency versions
  package-lock.json
  package.json
Labels: dependencies

#339 chore: Node.js v18
  .nvmrc
  package-lock.json
  package.json
Labels: dependencies

#340 chore: Dependabot suggested updates
  .github/dependabot.yml
  Gemfile.lock
  README.md
Labels: dependencies

#333 (1) feat: add network settings pre-settings and saga
  __tests__/sagas/networkSettings.test.ts
  src/App.js
  src/actions.js
  src/constants.js
  src/errorHandler.js
  src/reducers/reducer.init.js
  src/reducers/reducer.js
  src/sagas/featureToggle.js
  src/sagas/helpers.js
  src/sagas/networkSettings.js
  src/sagas/wallet.js
  src/workers/backgroundListeners.js
Labels: enhancement

#336 (2) refactor: constants settings to networkSettings state
  __tests__/sagas/networkSettings.test.ts
  src/constants.js
  src/sagas/helpers.js
  src/sagas/networkSettings.js
  src/sagas/pushNotification.js
  src/sagas/wallet.js
  src/sagas/walletConnect.js
  src/store.js
Labels: enhancement

#337 (3) refactor: hardcoded explorer link to networkSettings explorerUrl
  src/components/PublicExplorerListButton.js
  src/utils.js
Labels: enhancement

#338 (4) feat: Add title to HathorList and refactor Settings page
  src/components/HathorList.js
  src/screens/Settings.js
Labels: enhancement

#362 fix: Dependabot yml file structure
  .github/dependabot.yml
Labels: bug

#346 (6) feat: add network settings flow stack
  src/App.js
  src/screens/NetworkSettings/NetworkSettingsFlowStack.js
  src/screens/NetworkSettings/index.js
  src/screens/Settings.js
Labels: enhancement

#347 (7) feat: add disclaimer screen
  src/screens/NetworkSettings/NetworkSettingsDisclaimerScreen.js
  src/screens/NetworkSettings/NetworkSettingsFlowStack.js
Labels: enhancement

#348 (8) feat: add presettings screen
  src/constants.js
  src/sagas/index.js
  src/screens/NetworkSettings/NetworkPreSettingsScreen.js
  src/screens/NetworkSettings/NetworkSettingsFlowStack.js
Labels: enhancement

#349 (9) fix: getWalletServiceNetwork function
  src/sagas/helpers.js
Labels: enhancement

#350 (10) feat: add custom network settings screen
  src/actions.js
  src/constants.js
  src/reducers/reducer.js
  src/sagas/helpers.js
  src/sagas/networkSettings.js
  src/screens/NetworkSettings/CustomNetworkSettingsScreen.js
  src/screens/NetworkSettings/NetworkPreSettingsScreen.js
  src/screens/NetworkSettings/NetworkSettingsFlowStack.js
Labels: enhancement

#351 (11) feat: set correctly the NetworkSettingsFlowStack
  src/screens/NetworkSettings/NetworkSettingsDisclaimerScreen.js
  src/screens/NetworkSettings/NetworkSettingsFlowStack.js
Labels: enhancement

#353 (13) feat: add feedback modal to presettings screen
  src/screens/NetworkSettings/NetworkPreSettingsScreen.js
  src/screens/NetworkSettings/helper.js
Labels: enhancement

#354 refactor: remove blank on pin screen
  src/screens/PinScreen.js
Labels: bug
