Repository HathorNetwork/hathor-wallet-mobile, pull requests merged in 2024-10, with the labels that each got.

#575 refactor: reown
  ios/Podfile.lock
  locale/da/texts.po
  locale/pt-br/texts.po
  locale/ru-ru/texts.po
  locale/texts.pot
  package-lock.json
  package.json
  shim.js
  src/App.js
  src/actions.js
  src/components/Reown/ApproveRejectModal.js
  src/components/Reown/ConnectModal.js
  src/components/Reown/CreateTokenModal.js
  src/components/Reown/CreateTokenRequest.js
  src/components/Reown/ModalButton.js
  src/components/Reown/NanoContract/DappContainer.js
  src/components/Reown/NanoContract/DeclineModal.js
  src/components/Reown/NanoContract/NanoContractActions.js
  src/components/Reown/NanoContract/NanoContractExecInfo.js
  src/components/Reown/NanoContract/NanoContractMethodArgs.js
  src/components/Reown/NanoContract/NewNanoContractTransactionModal.js
  src/components/Reown/NanoContract/NewNanoContractTransactionRequest.js
  src/components/Reown/NanoContract/SignOracleDataModal.js
  src/components/Reown/ReownModal.js
  src/components/Reown/SignMessageModal.js
  src/components/Reown/SignMessageRequest.js
  src/components/Reown/SignOracleDataRequest.js
  src/components/Reown/WarnDisclaimer.js
  src/components/Reown/theme.js
  src/components/TextValue.js
  src/config.js
  src/constants.js
  src/reducers/reducer.js
  src/sagas/index.js
  src/sagas/reown.js
  src/sagas/tokens.js
  src/screens/Reown/CreateTokenScreen.js
  src/screens/Reown/NewNanoContractTransactionScreen.js
  src/screens/Reown/ReownList.js
  src/screens/Reown/ReownManual.js
  src/screens/Reown/ReownScan.js
  src/screens/Reown/SignMessageRequestScreen.js
  src/screens/Reown/SignOracleDataRequestScreen.js
  src/screens/Reown/SuccessFeedbackScreen.js
  src/screens/Settings.js
Labels: enhancement

#584 fix: Bump script rc regex
  scripts/bump-version.js
Labels: bug

#582 feat: Android target 34
  android/build.gradle
Labels: dependencies

#585 docs: Minor improvements to QA
  QA.md
  QA_CUSTOM_NETWORK.md
  QA_PUSH_NOTIFICATION.md
Labels: documentation
