Repository HathorNetwork/hathor-wallet-mobile, pull requests merged in 2025-07, with the labels that each got.

#691 refactor: new modals
  locale/da/texts.po
  locale/pt-br/texts.po
  locale/ru-ru/texts.po
  locale/texts.pot
  package-lock.json
  package.json
  src/components/BackdropModal.js
  src/components/GlobalErrorModal.js
  src/components/HathorModal.js
  src/components/ModalBase.js
  src/components/Reown/ApproveRejectModal.js
  src/components/TxDetailsModal.js
  src/screens/BackupWords.js
  src/screens/SendAmountInput.js
  src/screens/SendConfirmScreen.js
Labels: documentation

#689 feat: updated sign oracle data
  locale/da/texts.po
  locale/pt-br/texts.po
  locale/ru-ru/texts.po
  locale/texts.pot
  package-lock.json
  package.json
  src/components/BackdropModal.js
  src/components/CopyClipboard.js
  src/components/GlobalErrorModal.js
  src/components/HathorModal.js
  src/components/ModalBase.js
  src/components/Reown/ApproveRejectModal.js
  src/components/Reown/NanoContract/BaseNanoContractRequest.js
  src/components/Reown/NanoContract/NanoContractMethodArgs.js
  src/components/Reown/NanoContract/SignedDataDisplay.js
  src/components/Reown/RequestConfirmationModal.js
  src/components/Reown/SignOracleDataRequest.js
  src/components/Reown/theme.js
  src/components/TxDetailsModal.js
  src/screens/BackupWords.js
  src/screens/SendAmountInput.js
  src/screens/SendConfirmScreen.js
Labels: enhancement

#693 feat: bravo testnet
  src/constants.js
Labels: enhancement

#658 refactor: big int
  flake.nix
  locale/da/texts.po
  locale/pt-br/texts.po
  locale/ru-ru/texts.po
  locale/texts.pot
  package-lock.json
  package.json
  patches/@hathor+wallet-lib+2.6.0.patch
  src/App.js
  src/actions.js
  src/components/AmountTextInput.js
  src/components/BackdropModal.js
  src/components/CopyClipboard.js
  src/components/GlobalErrorModal.js
  src/components/HathorModal.js
  src/components/ModalBase.js
  src/components/NanoContract/NanoContractTransactionActionListItem.js
  src/components/NewPaymentRequest.js
  src/components/PushTxDetailsModal.js
  src/components/Reown/ApproveRejectModal.js
  src/components/Reown/ConnectModal.js
  src/components/Reown/CreateNanoContractCreateTokenTxModal.js
  src/components/Reown/CreateNanoContractCreateTokenTxRequest.js
  src/components/Reown/CreateTokenModal.js
  src/components/Reown/CreateTokenRequest.js
  src/components/Reown/InsufficientFundsModal.js
  src/components/Reown/NanoContract/BaseNanoContractRequest.js
  src/components/Reown/NanoContract/DappContainer.js
  src/components/Reown/NanoContract/NanoContractActions.js
  src/components/Reown/NanoContract/NanoContractMethodArgs.js
  src/components/Reown/NanoContract/NewNanoContractTransactionModal.js
  src/components/Reown/NanoContract/NewNanoContractTransactionRequest.js
  src/components/Reown/NanoContract/SignedDataDisplay.js
  src/components/Reown/ReownModal.js
  src/components/Reown/RequestConfirmationModal.js
  src/components/Reown/SendTransactionModal.js
  src/components/Reown/SendTransactionRequest.js
  src/components/Reown/SignMessageModal.js
  src/components/Reown/SignOracleDataRequest.js
  src/components/Reown/theme.js
  src/components/TokenSelect.js
  src/components/TxDetailsModal.js
  src/constants.js
  src/hooks/navigation.js
  src/reducers/reducer.js
  src/sagas/reown.js
  src/sagas/tokens.js
  src/screens/BackupWords.js
  src/screens/CreateTokenAmount.js
  src/screens/CreateTokenConfirm.js
  src/screens/MainScreen.js
  src/screens/PaymentRequestDetail.js
  src/screens/Reown/CreateNanoContractCreateTokenTxScreen.js
  src/screens/Reown/SendTransactionRequestScreen.js
  src/screens/SendAmountInput.js
  src/screens/SendConfirmScreen.js
  src/utils.js
Labels: enhancement

#696 fix: nano contract history was using nc_pubkey
  src/sagas/nanoContract.js
Labels: bug

#699 fix: multiple modal nc address seletor
  src/components/NanoContract/EditAddressModal.js
  src/components/NanoContract/NanoContractDetailsHeader.js
  src/components/NanoContract/SelectAddressModal.js
Labels: bug

#702 chore: update rpc lib
  package-lock.json
  package.json
Labels: enhancement

#707 fix: rc3 fixes
  src/components/FeedbackContent.js
  src/components/HathorModal.js
  src/components/NanoContract/NanoContractsList.js
  src/components/PushTxDetailsModal.js
  src/sagas/wallet.js
Labels: bug

#713 fix: Payment request bigint issues
  flake.nix
  src/reducers/reducer.js
Labels: bug
